#include QMK_KEYBOARD_H
#include "custom_keys.h"

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

    [0] = LAYOUT(KC_Q, KC_W, KC_F, KC_P, KC_B, KC_J, KC_L, KC_U, KC_Y, KC_BSPC, KC_A, KC_R, LT(0, KC_S), KC_T, KC_G, KC_M, KC_N, KC_E, KC_I, KC_O, KC_Z, LT(0, KC_X), LT(0, KC_C), KC_D, LT(0, KC_V), KC_K, KC_H, LT(0, KC_LBRC), LT(0, KC_RBRC), KC_SLSH, LSFT_T(KC_ENT), KC_SPC, OPT_T(KC_COMM), LT(1, KC_DOT)),

    [1] = LAYOUT(KC_PMNS, KC_PPLS, KC_7, KC_8, KC_9, KC_MINS, KC_EQL, KC_F3, KC_F12, TO(2), KC_PSLS, KC_PAST, KC_4, KC_5, KC_6, KC_SCLN, KC_QUOT, KC_BSLS, KC_SLSH, TO(3), KC_PENT, KC_0, KC_1, KC_2, KC_3, KC_LBRC, KC_RBRC, KC_COMM, KC_DOT, TO(4), LSFT_T(KC_ENT), KC_SPC, KC_NO, KC_TRNS),

    [2] = LAYOUT(KC_ESC, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, MKR_QUOTE, MKR_CURLY, KC_TRNS, KC_TRNS, TO(2), KC_TAB, KC_WH_U, KC_BTN1, KC_MS_U, KC_BTN2, MKR_ARROW, MKR_ARROW_FN, KC_GRV, KC_SLSH, TO(3), KC_DEL, KC_WH_D, KC_MS_L, KC_MS_D, KC_MS_R, MKR_BRACKET, MKR_ARRAY, KC_COMM, KC_DOT, TO(4), LSFT_T(KC_ENT), KC_SPC, LAY_DEF_2, TO(0)),

    [3] = LAYOUT(KC_F1, KC_F2, KC_F3, KC_F4, RGB_TOG, KC_BRID, KC_BRIU, KC_VOLD, KC_VOLU, TO(2), KC_F5, KC_F6, KC_F7, KC_F8, RGB_INC, KC_INS, KC_HOME, KC_PGUP, RGB_INC, TO(3), KC_F9, KC_F10, KC_F11, KC_F12, RGB_DEC, KC_DEL, KC_END, KC_PGDN, RGB_DEC, TO(4), LSFT_T(KC_ENT), KC_SPC, LAY_DEF_3, TO(0)),

    [4] = LAYOUT(KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_ENT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_NO, KC_NO, KC_NO, KC_LSFT, KC_SPC, KC_LALT, TO(0))};
